# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrados',
            fields=[
                ('reg_nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('reg_raedad', models.CharField(max_length=50)),
                ('reg_resgua', models.CharField(max_length=200)),
                ('reg_nacade', models.CharField(max_length=30)),
                ('reg_organi', models.CharField(max_length=200)),
                ('reg_correo', models.CharField(max_length=100)),
                ('reg_fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registrados',
                'managed': False,
            },
        ),
    ]
