# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrados',
            options={},
        ),
    ]
